version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    post_install:
      - pip install sphinx-book-theme
      - pip install matplotlib

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: source/conf.py






