version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"



python:
  install:
    - requirements: requirements.txt



sphinx:
  configuration: source/conf.py

commands:
  - pip list
  - python -c "from pymembrane.membrane import membrane; print(membrane)"







